### ISSUE TITLE
http://localhost:8080/bonita/apps/procurement

### ISSUE THREAD

**Issue by vetriselvan-k** [Bonitasoft-Community/procurement-example#2]
when I access the below URL after installing the procurement example in bonita, what is the userid and password I should use?. please help me.

http://localhost:8080/bonita/apps/procurement

**Comment by FunTomAS74** [comment]
I just tried the example with Bonita 7.5.4 Community and it worked really fine.
I wasn't asked for a login, but normally it's Walter Bates by default, so if you are asked to login, just use:
Login : walter.bates
Password: bpm 
("bpm" is the PW for all example users!)

**Comment by amottier** [comment]
I confirm that the default user is walter.bates with password: bpm
If you click on the Portal button in Bonita Studio toolbar you will be automatically logged in with this user by default.
